services:
  - type: web
    name: mariage-africain
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 18 